# Generated by Django 3.2.6 on 2021-09-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_comment_author_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
